pipelines:
  default:
    - step:
        image: php:7.4
        caches:
          - composer
        services:
          - pgsql11
          - pgsql12
          - mysql5
          - mysql8
        script:
          - apt-get update && apt-get install -y --no-install-recommends unzip ssh-client git-core
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpunit --configuration .

definitions:
  services:
    pgsql11:
      memory: 512
      image: postgres:11.5
      variables:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: test

    pgsql12:
      memory: 512
      image: postgres:12
      variables:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: test

    mysql5:
      memory: 512
      image: mysql/mysql-server:5.5
      variables:
        MYSQL_DATABASE: 'test'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'

    mysql8:
      memory: 512
      image: mysql:8
      variables:
        MYSQL_DATABASE: 'test'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
